### PR TITLE
net35 compabillity

### PR DESCRIPTION
**Pull request by viceice**
We require net35 compabillity. Currently we use a custom build. Can we add this to the official package?

### CODE REVIEW

**Comment by adamreeve** [comment]
Sure, this looks good thanks 👍

**Comment by adamreeve** [comment]
I've published this to NuGet as version 1.1.0, let me know if there are any issues

**Comment by viceice** [comment]
I will test it on Monday. Thanks.

**Comment by viceice** [comment]
It's working fine 👍

**Pull request merged**
